<a href="https://colab.research.google.com/github/GauravGoel97/python/blob/master/IMDBproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("/content/movies.csv")

Q1. How do we load a dataset and see first five rows?

> Add blockquote

In [8]:
df.head(5)

,id,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description
0,tt0068646,The Godfather,1972,9.2,R,175 min,"Crime, Drama",1798749,"134,966,411",nm0000338,Francis Ford Coppola,"nm0000008,nm0000199,nm0001001,nm0000473","Marlon Brando,Al Pacino,James Caan,Diane Keaton",The aging patriarch of an organized crime dyna...
1,tt5113044,Minions: The Rise of Gru,2022,7.3,PG,87 min,"Animation, Adventure, Comedy","1,220","134,966,411","nm0049633,nm1556070,nm3646390","Kyle Balda,Brad Ableson,Jonathan del Val","nm0136797,nm1853544,nm0000273,nm0378245","Steve Carell,Pierre Coffin,Alan Arkin,Taraji P...",The untold story of one twelve-year-old's drea...
2,tt7657566,Death on the Nile,2022,6.3,PG-13,127 min,"Crime, Drama, Mystery","121,063","134,966,411",nm0000110,Kenneth Branagh,"nm5290643,nm0000906,nm0000110,nm1258970","Tom Bateman,Annette Bening,Kenneth Branagh,Rus...","While on vacation on the Nile, Hercule Poirot ..."
3,tt8115900,The Bad Guys,2022,6.9,PG,100 min,"Animation, Adventure, Comedy","23,090","134,966,411",nm2010048,Pierre Perifel,"nm0005377,nm0549505,nm5377144,nm0732497","Sam Rockwell,Marc Maron,Awkwafina,Craig Robinson",Several reformed yet misunderstood criminal an...
4,tt10809742,Collision,2022,3.8,TV-MA,99 min,"Crime, Drama, Thriller",656,"134,966,411",nm1926494,Fabien Martorell,"nm1339181,nm0456810,nm12651040,nm7357127","Tessa Jubber,Langley Kirkwood,Zoey Sneedon,Bon...",Freedom always comes at a price.

Q2. How do we load a dataset and see last five rows?

In [9]:
df.tail(5)

,id,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description
19803,tt0459423,Kahaani Gudiya Ki...: True Story of a Woman,2008,6.2,Not Rated,112 min,"Biography, Drama",41,"44,435",nm1909606,Prabhakar Shukla,"nm0244890,nm0952232,nm1056425,nm6389513","Divya Dutta,Arif Zakaria,Rajpal Naurang Yadav,...","A tragic saga about a woman named Gudiya, whos..."
19804,tt0119621,Mark Twain's America in,1998,6.5,G,52 min,"Documentary, Biography",48,"2,281,741",nm0522844,Stephen Low,"nm0000843,nm0640297,nm4700843,nm1838044","Anne Bancroft,Dennis O'Connor,Kim Parr,LeeAnn ...",Interweaves Twain's life and times with the li...
19805,tt0168950,Let It Come Down: The Life of Paul Bowles,1998,6.9,Not Rated,75 min,"Documentary, Biography",125,"9,188",nm0047028,Jennifer Baichwal,"nm0101247,nm0123221,nm0155822,nm0159383","Paul Bowles,William S. Burroughs,Cherifa,Moham...",Add a Plot
19806,tt0267563,Hybrid,2000,7.4,Not Rated,92 min,"Documentary, Biography",146,"159,403","/name/nm0566144/,/name/nm1084921/","Monteith McCollum,Milford Beeghly",nm1084921,Milford Beeghly,The life story of Milford Beeghly: Iowa farmer...
19807,tt0116481,Hands on a Hardbody: The Documentary,1997,7.6,PG,98 min,"Documentary, Comedy, Drama",2167,"492,876",nm0082835,S.R. Bindler,"nm0021057,nm1828145,nm0185044,nm0190040","Sid Allen,Brent Baskin,Greg Cox,J.C. Crum",Twenty-four contestants compete in an enduranc...

In [10]:
df.sample(1000)

,id,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description
15530,tt0088933,Cocoon,1985,6.7,PG-13,117 min,"Comedy, Drama, Sci-Fi",62977,"76,113,124",nm0000165,Ron Howard,"nm0000747,nm0000979,nm0002025,nm0001133","Don Ameche,Wilford Brimley,Hume Cronyn,Brian D...",When a group of trespassing seniors swim in a ...
6257,tt0090917,Deadly Friend,1986,5.5,R,91 min,"Drama, Horror, Sci-Fi",7766,"8,988,731",nm0000127,Wes Craven,"nm0479612,nm0001785,nm0789326,nm0878645","Matthew Labyorteaux,Kristy Swanson,Michael Sha...",After his friend is killed by her abusive fath...
13858,tt0082199,Condorman,1981,5.7,PG,90 min,"Action, Adventure, Comedy","4,940","7,680,000",nm0418986,Charles Jarrott,"nm0186903,nm0001657,nm0000324,nm0358996","Michael Crawford,Oliver Reed,Barbara Carrera,J...",Cartoonist Woody becomes the superhero he draw...
14947,tt2474310,Land of Storms,2014,6.8,Unrated,105 min,"Drama, Romance, Sport","4,123","10,178,331",nm2414670,Ádám Császi,"nm5364484,nm3944077,nm0773308,nm0127102","András Sütö,Ádám Varga,Sebastian Urzendowsky,E...",Szabolcs quits football against his father's w...
13994,tt0431213,Lassie,2005,6.7,PG,100 min,"Adventure, Comedy, Drama",4428,"652,163",nm0836430,Charles Sturridge,"nm0001487,nm0608090,nm0000564,nm0227759","John Lynch,Samantha Morton,Peter O'Toole,Peter...",A family in financial crisis is forced to sell...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9569,tt0044926,Moulin Rouge,1952,7.0,Not Rated,119 min,"Biography, Drama, Music",5566,"11,810,000",nm0001379,John Huston,"nm0001207,nm0001248,nm0282530,nm0634488","José Ferrer,Zsa Zsa Gabor,Suzanne Flon,Claude ...",Fictional account of French artist Henri de To...
2004,tt0783238,The Dead Girl,2006,6.6,R,85 min,"Crime, Drama, Mystery",15387,"17,311",nm0597673,Karen Moncrieff,"nm0001057,nm0005261,nm0001315,nm0001453","Toni Collette,Brittany Murphy,Marcia Gay Harde...",The clues to a young woman's death come togeth...
8176,tt1835955,Errors of the Human Body,2012,5.2,Unrated,101 min,"Drama, Horror, Mystery","2,309","21,464",nm1142688,Eron Sheean,"nm1002664,nm0378932,nm1319365,nm0562201","Michael Eklund,Karoline Herfurth,Tómas Lemarqu...",When a potentially lethal virus is created wit...
18698,tt0192023,Finder's Fee,2001,6.3,R,100 min,"Drama, Thriller","2,452","10,037,390",nm0698251,Jeff Probst,"nm0005292,nm0005351,nm0005231,nm0005318","Erik Palladino,Ryan Reynolds,Dash Mihok,Carly ...",A man finds a wallet containing a winning lott...
19519,tt9558612,PM Narendra Modi,2019,2.9,Not Rated,136 min,"Biography, Drama","7,812","411,897",nm1293225,Omung Kumar,"nm1059103,nm1259084,nm1069587,nm0820283","Vivek Oberoi,Manoj Joshi,Darshan Kumaar,Anjan ...",Biography of India's Prime Minister Shri Naren...

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19808 entries, 0 to 19807
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              19808 non-null  object
 1   name            19808 non-null  object
 2   year            19808 non-null  int64
 3   rating          19808 non-null  float64
 4   certificate     19808 non-null  object
 5   duration        19808 non-null  object
 6   genre           19808 non-null  object
 7   votes           19808 non-null  object
 8   gross_income    19808 non-null  object
 9   directors_id    19808 non-null  object
 10  directors_name  19808 non-null  object
 11  stars_id        19808 non-null  object
 12  stars_name      19808 non-null  object
 13  description     19808 non-null  object
dtypes: float64(1), int64(1), object(12)
memory usage: 2.1+ MB

In [12]:
df.describe()

               year        rating
count  19808.000000  19808.000000
mean    1995.546597      6.041973
std       22.801725      1.206831
min     1894.000000      1.100000
25%     1983.000000      5.300000
50%     2003.000000      6.200000
75%     2014.000000      6.900000
max     2022.000000      9.700000

In [13]:
df.duplicated().sum()  ##df.duplicated() will show the values as True/false while df.duplicated().sum() will give the sum of all the duplicate values

np.int64(0)

In [14]:
df.isnull().sum()  ##similary df.isnull() will show the values as True/false while df.null().sum() will give the sum of all the null values (if any)

id                0
name              0
year              0
rating            0
certificate       0
duration          0
genre             0
votes             0
gross_income      0
directors_id      0
directors_name    0
stars_id          0
stars_name        0
description       0
dtype: int64

3. How can we clean the duration column?

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19808 entries, 0 to 19807
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              19808 non-null  object
 1   name            19808 non-null  object
 2   year            19808 non-null  int64
 3   rating          19808 non-null  float64
 4   certificate     19808 non-null  object
 5   duration        19808 non-null  object
 6   genre           19808 non-null  object
 7   votes           19808 non-null  object
 8   gross_income    19808 non-null  object
 9   directors_id    19808 non-null  object
 10  directors_name  19808 non-null  object
 11  stars_id        19808 non-null  object
 12  stars_name      19808 non-null  object
 13  description     19808 non-null  object
dtypes: float64(1), int64(1), object(12)
memory usage: 2.1+ MB

In [16]:
df["year"].mode()[0]

np.int64(2018)

In [17]:
##df["duration"].mean()   ##why error? data type is string, should be int or float.

In [18]:
df["duration"] = df["duration"].str.replace("min","")

In [19]:
df["duration"] = df["duration"].str.replace(",", "")

In [20]:
print(df['duration'].dtype)

object

In [21]:
df["duration"] = df["duration"].astype(int)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19808 entries, 0 to 19807
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              19808 non-null  object
 1   name            19808 non-null  object
 2   year            19808 non-null  int64
 3   rating          19808 non-null  float64
 4   certificate     19808 non-null  object
 5   duration        19808 non-null  int64
 6   genre           19808 non-null  object
 7   votes           19808 non-null  object
 8   gross_income    19808 non-null  object
 9   directors_id    19808 non-null  object
 10  directors_name  19808 non-null  object
 11  stars_id        19808 non-null  object
 12  stars_name      19808 non-null  object
 13  description     19808 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 2.1+ MB

In [23]:
df["duration"].mean()

np.float64(101.77796849757674)

In [24]:
df["duration"].median()

98.0

In [25]:
df["duration"].var()

1864.401954130177

In [26]:
df["duration"].std()

43.17872108029807

In [27]:
df["duration"].mode()[0]

np.int64(90)

In [28]:
##Q4. How do we clean the `gross` column and `votes` column?
##convert 'votes' and 'gross income' to integers

In [29]:
df["votes"] = df["votes"].str.replace(",","")

In [30]:
df["votes"] = df["votes"].astype(int)

In [31]:
print(df["votes"])

0        1798749
1           1220
2         121063
3          23090
4            656
          ...
19803         41
19804         48
19805        125
19806        146
19807       2167
Name: votes, Length: 19808, dtype: int64

In [32]:
df["gross_income"] = df["gross_income"].str.replace("$","")

In [33]:
df["gross_income"] = df["gross_income"].str.replace("M","")

In [34]:
df["gross_income"] = df["gross_income"].str.replace(",","")

In [35]:
df["gross_income"] = df["gross_income"].astype(float)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19808 entries, 0 to 19807
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              19808 non-null  object
 1   name            19808 non-null  object
 2   year            19808 non-null  int64
 3   rating          19808 non-null  float64
 4   certificate     19808 non-null  object
 5   duration        19808 non-null  int64
 6   genre           19808 non-null  object
 7   votes           19808 non-null  int64
 8   gross_income    19808 non-null  float64
 9   directors_id    19808 non-null  object
 10  directors_name  19808 non-null  object
 11  stars_id        19808 non-null  object
 12  stars_name      19808 non-null  object
 13  description     19808 non-null  object
dtypes: float64(2), int64(3), object(9)
memory usage: 2.1+ MB

In [37]:
#Q5 how many missing values are there in each column?

df.isnull().sum()

id                0
name              0
year              0
rating            0
certificate       0
duration          0
genre             0
votes             0
gross_income      0
directors_id      0
directors_name    0
stars_id          0
stars_name        0
description       0
dtype: int64

In [38]:
###Q7 Find the hidden gems (high ratings, low votes)?

In [39]:
df.describe()

               year        rating      duration         votes  gross_income
count  19808.000000  19808.000000  19808.000000  1.980800e+04  1.980800e+04
mean    1995.546597      6.041973    101.777968  3.694303e+04  1.682198e+07
std       22.801725      1.206831     43.178721  1.129755e+05  4.642034e+07
min     1894.000000      1.100000      1.000000  5.000000e+00  0.000000e+00
25%     1983.000000      5.300000     90.000000  1.058000e+03  1.196010e+05
50%     2003.000000      6.200000     98.000000  4.233000e+03  1.158192e+06
75%     2014.000000      6.900000    111.000000  2.045350e+04  1.243278e+07
max     2022.000000      9.700000   5220.000000  2.574832e+06  9.366622e+08

In [40]:
df['rating'] > 6.9

0         True
1         True
2        False
3        False
4        False
         ...
19803    False
19804    False
19805    False
19806     True
19807     True
Name: rating, Length: 19808, dtype: bool

In [41]:
df[df['rating'] > 6.9]

,id,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description
0,tt0068646,The Godfather,1972,9.2,R,175,"Crime, Drama",1798749,134966411.0,nm0000338,Francis Ford Coppola,"nm0000008,nm0000199,nm0001001,nm0000473","Marlon Brando,Al Pacino,James Caan,Diane Keaton",The aging patriarch of an organized crime dyna...
1,tt5113044,Minions: The Rise of Gru,2022,7.3,PG,87,"Animation, Adventure, Comedy",1220,134966411.0,"nm0049633,nm1556070,nm3646390","Kyle Balda,Brad Ableson,Jonathan del Val","nm0136797,nm1853544,nm0000273,nm0378245","Steve Carell,Pierre Coffin,Alan Arkin,Taraji P...",The untold story of one twelve-year-old's drea...
5,tt0071562,The Godfather Part II,1974,9.0,R,202,"Crime, Drama",1239038,57300000.0,nm0000338,Francis Ford Coppola,"nm0000199,nm0000134,nm0000380,nm0000473","Al Pacino,Robert De Niro,Robert Duvall,Diane K...",The early life and career of Vito Corleone in ...
9,tt0071771,The Longest Yard,1974,7.1,R,121,"Comedy, Crime, Drama",19000,7130696.0,nm0000736,Robert Aldrich,"nm0000608,nm0000734,nm0491590,nm0175700","Burt Reynolds,Eddie Albert,Ed Lauter,Michael C...",A sadistic warden asks a former pro quarterbac...
10,tt0993846,The Wolf of Wall Street,2013,8.2,R,180,"Biography, Comedy, Crime",1352516,116900694.0,nm0000217,Martin Scorsese,"nm0000138,nm1706767,nm3053338,nm0000190","Leonardo DiCaprio,Jonah Hill,Margot Robbie,Mat...","Based on the true story of Jordan Belfort, fro..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19800,tt0044917,Amazing Monsieur Fabre,1951,7.0,Approved,90,"Biography, Comedy, Drama",64,33024.0,nm0224543,Henri Diamant-Berger,"nm0294382,nm0479626,nm0709536,nm0845969","Pierre Fresnay,Elina Labourdette,André Randall...",Pierre Fresnay plays the title role of a dedic...
19801,tt1334479,"Yoo-Hoo, Mrs. Goldberg",2009,7.4,Unrated,92,"Documentary, Biography",236,1133662.0,nm0447476,Aviva Kempner,"nm0073764,nm3571106,nm1675671,nm0046029","Gertrude Berg,Lewis Berg,Sara Chase,Ruth Bader...","The story of the actress, writer, and broadcas..."
19802,tt1518255,Raw Faith,2010,8.3,Not Rated,94,"Documentary, Biography, Drama",71,1486.0,"/name/nm0927286/,/name/nm3628867/","Wm. Peter Wiedensmith,Marilyn Sewell",nm3628867,Marilyn Sewell,This surprisingly open and revealing documenta...
19806,tt0267563,Hybrid,2000,7.4,Not Rated,92,"Documentary, Biography",146,159403.0,"/name/nm0566144/,/name/nm1084921/","Monteith McCollum,Milford Beeghly",nm1084921,Milford Beeghly,The life story of Milford Beeghly: Iowa farmer...
19807,tt0116481,Hands on a Hardbody: The Documentary,1997,7.6,PG,98,"Documentary, Comedy, Drama",2167,492876.0,nm0082835,S.R. Bindler,"nm0021057,nm1828145,nm0185044,nm0190040","Sid Allen,Brent Baskin,Greg Cox,J.C. Crum",Twenty-four contestants compete in an enduranc...

In [42]:
df["votes"].mean()

np.float64(36943.027160743135)

In [43]:
df["votes"].median()

4233.0

In [44]:
df[df['votes'] < 1058]

,id,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description
4,tt10809742,Collision,2022,3.8,TV-MA,99,"Crime, Drama, Thriller",656,134966411.0,nm1926494,Fabien Martorell,"nm1339181,nm0456810,nm12651040,nm7357127","Tessa Jubber,Langley Kirkwood,Zoey Sneedon,Bon...",Freedom always comes at a price.
33,tt13479592,Centaur,2022,5.3,TV-MA,89,"Action, Adventure, Crime",791,58009200.0,nm0130714,Daniel Calparsoro,"nm3856284,nm9603580,nm10257702,nm5379183","Àlex Monner,Begoña Vargas,Abraham Pérez Fernán...","Rafa's hooked on the pure, fiery feelings he g..."
47,tt1551614,Blowback,2022,4.4,R,93,"Action, Crime, Thriller",199,74283625.0,nm0847749,Tibor Takács,"nm1330276,nm1544217,nm6029604,nm0541909","Randy Couture,Cam Gigandet,Michele Plaia,Louis...","After planning a perfect heist, Nick is ready ..."
463,tt0148615,Play Motel,1979,4.8,X,93,"Crime, Horror, Mystery",545,69304264.0,nm0307391,Mario Gariazzo,"nm0522590,nm0729940,nm0193892,nm0029738","Ray Lovelock,Anna Maria Rizzoli,Mario Cutini,A...",A reporter and his girlfriend investigate deat...
565,tt0026184,The Case of the Curious Bride,1935,6.6,Passed,80,"Comedy, Crime, Drama",1031,2395231.0,nm0002031,Michael Curtiz,"nm0929925,nm0512267,nm0940579,nm0230068","Warren William,Margaret Lindsay,Donald Woods,C...",Perry interrupts his vacation plans when an ex...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19802,tt1518255,Raw Faith,2010,8.3,Not Rated,94,"Documentary, Biography, Drama",71,1486.0,"/name/nm0927286/,/name/nm3628867/","Wm. Peter Wiedensmith,Marilyn Sewell",nm3628867,Marilyn Sewell,This surprisingly open and revealing documenta...
19803,tt0459423,Kahaani Gudiya Ki...: True Story of a Woman,2008,6.2,Not Rated,112,"Biography, Drama",41,44435.0,nm1909606,Prabhakar Shukla,"nm0244890,nm0952232,nm1056425,nm6389513","Divya Dutta,Arif Zakaria,Rajpal Naurang Yadav,...","A tragic saga about a woman named Gudiya, whos..."
19804,tt0119621,Mark Twain's America in,1998,6.5,G,52,"Documentary, Biography",48,2281741.0,nm0522844,Stephen Low,"nm0000843,nm0640297,nm4700843,nm1838044","Anne Bancroft,Dennis O'Connor,Kim Parr,LeeAnn ...",Interweaves Twain's life and times with the li...
19805,tt0168950,Let It Come Down: The Life of Paul Bowles,1998,6.9,Not Rated,75,"Documentary, Biography",125,9188.0,nm0047028,Jennifer Baichwal,"nm0101247,nm0123221,nm0155822,nm0159383","Paul Bowles,William S. Burroughs,Cherifa,Moham...",Add a Plot
19806,tt0267563,Hybrid,2000,7.4,Not Rated,92,"Documentary, Biography",146,159403.0,"/name/nm0566144/,/name/nm1084921/","Monteith McCollum,Milford Beeghly",nm1084921,Milford Beeghly,The life story of Milford Beeghly: Iowa farmer...

In [45]:
df[(df['rating'] > 6.9) & (df['votes'] < 1058)]

,id,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description
3423,tt4106286,Tiny Detectives,2014,7.2,TV-14,2,"Short, Comedy, Crime",536,1501277.0,nm0124089,Andrew Bush,"nm0680983,nm0544718,nm1930273,nm7534064","Elliot Page,Kate Mara,DeMorge Brown,Jaclyn Fle...","A parody of True Detective about two short, fe..."
3502,tt0042953,Shakedown,1950,7.0,Approved,80,"Crime, Drama, Film-Noir",346,6310.0,nm0678928,Joseph Pevney,"nm0003318,nm0235627,nm0002046,nm0862937","Howard Duff,Peggy Dow,Brian Donlevy,Lawrence T...",Unscrupulous and opportunistic San Francisco n...
3522,tt0070552,High Crime,1973,7.0,R,100,"Crime, Drama, Thriller",885,1404.0,nm0144758,Enzo G. Castellari,"nm0626259,nm0721073,nm0926235,nm0090521","Franco Nero,Fernando Rey,James Whitmore,Delia ...",An Italian police inspector matches wits with ...
3594,tt0246879,Qurbani,1980,7.0,Not Rated,157,"Action, Crime, Drama",886,398420.0,nm0451211,Feroz Khan,"nm0451211,nm0451396,nm0023868,nm0451166","Feroz Khan,Vinod Khanna,Zeenat Aman,Amjad Khan",Two friends live happily until misunderstandin...
3980,tt13634096,The Bacon Hair,2020,8.5,TV-14,76,"Animation, Action, Adventure",90,852206.0,nm9762716,ObliviousHD,"nm5055725,nm10194796,nm12142163,nm0746445","Leah Ashley,Tom Aglio,Gen Sherard,Graham Rowat",Surrounded by towering walls and patrolled by ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19799,tt1486548,Ahead of Time: The Extraordinary Journey of Ru...,2009,7.9,Not Rated,73,"Documentary, Biography",77,33024.0,nm0725053,Robert Richman,"nm0344295,nm4271124,nm0811750,nm4270360","Ruth Gruber,Louisa Herz Leopold,Dava Sobel,Lee...",A documentary on the remarkable life of Ruth G...
19800,tt0044917,Amazing Monsieur Fabre,1951,7.0,Approved,90,"Biography, Comedy, Drama",64,33024.0,nm0224543,Henri Diamant-Berger,"nm0294382,nm0479626,nm0709536,nm0845969","Pierre Fresnay,Elina Labourdette,André Randall...",Pierre Fresnay plays the title role of a dedic...
19801,tt1334479,"Yoo-Hoo, Mrs. Goldberg",2009,7.4,Unrated,92,"Documentary, Biography",236,1133662.0,nm0447476,Aviva Kempner,"nm0073764,nm3571106,nm1675671,nm0046029","Gertrude Berg,Lewis Berg,Sara Chase,Ruth Bader...","The story of the actress, writer, and broadcas..."
19802,tt1518255,Raw Faith,2010,8.3,Not Rated,94,"Documentary, Biography, Drama",71,1486.0,"/name/nm0927286/,/name/nm3628867/","Wm. Peter Wiedensmith,Marilyn Sewell",nm3628867,Marilyn Sewell,This surprisingly open and revealing documenta...
19806,tt0267563,Hybrid,2000,7.4,Not Rated,92,"Documentary, Biography",146,159403.0,"/name/nm0566144/,/name/nm1084921/","Monteith McCollum,Milford Beeghly",nm1084921,Milford Beeghly,The life story of Milford Beeghly: Iowa farmer...

In [46]:
##Q8 Find the overhyped movies --low ratings-high gross
df[(df['rating']<5.3) & (df['gross_income']>12432780)]

,id,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description
4,tt10809742,Collision,2022,3.8,TV-MA,99,"Crime, Drama, Thriller",656,134966411.0,nm1926494,Fabien Martorell,"nm1339181,nm0456810,nm12651040,nm7357127","Tessa Jubber,Langley Kirkwood,Zoey Sneedon,Bon...",Freedom always comes at a price.
18,tt11656220,Midnight in the Switchgrass,2021,4.4,R,99,"Action, Crime, Thriller",6827,107928762.0,nm0256542,Randall Emmett,"nm0386472,nm1083271,nm0000246,nm0001305","Emile Hirsch,Megan Fox,Bruce Willis,Lukas Haas",An FBI agent and Florida State officer team up...
37,tt6749318,Speed Kills,2018,4.2,R,102,"Action, Crime, Drama",3381,130742922.0,nm9928566,Jodi Scurfield,"nm0000237,nm0935395,nm0261170,nm0922995","John Travolta,Katheryn Winnick,Jennifer Esposi...",Speedboat racing champion and multimillionaire...
40,tt5433138,F9: The Fast Saga,2021,5.2,PG-13,143,"Action, Crime, Thriller",125648,173202780.0,nm0510912,Justin Lin,"nm0004874,nm0735442,nm0108287,nm0879085","Vin Diesel,Michelle Rodriguez,Jordana Brewster...",Dom and the crew must take on an international...
47,tt1551614,Blowback,2022,4.4,R,93,"Action, Crime, Thriller",199,74283625.0,nm0847749,Tibor Takács,"nm1330276,nm1544217,nm6029604,nm0541909","Randy Couture,Cam Gigandet,Michele Plaia,Louis...","After planning a perfect heist, Nick is ready ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18575,tt1389139,When the Bough Breaks,2016,5.1,PG-13,107,"Drama, Thriller",6974,29703843.0,nm0143984,Jon Cassar,"nm0004820,nm0356021,nm0539082,nm0931324","Morris Chestnut,Regina Hall,Romany Malco,Micha...",A surrogate mom for a couple becomes dangerous...
18615,tt8170298,John Henry,2020,3.6,R,91,"Drama, Thriller",2368,21082165.0,nm3112158,Will Forbes,"nm0187719,nm4175452,nm0524839,nm0286010","Terry Crews,Jamila Velazquez,Ludacris,Ken Foree",When two immigrant kids on the run from his fo...
18616,tt6469960,An Imperfect Murder,2017,3.2,R,71,Thriller,1666,15156200.0,nm0864812,James Toback,"nm1092227,nm0000285,nm0001301,nm0131974","Sienna Miller,Alec Baldwin,Charles Grodin,Coll...",An actress's nightmare about killing her ex-bo...
18717,tt1859573,Pretty Obsession,2012,4.2,Not Rated,89,Thriller,193,12974636.0,nm0062341,Michael Baumgarten,"nm4386106,nm4672255,nm2373963,nm2949570","Brittany Nicole Kovler,Lydia Pritchett,Danny P...",A pretty eighteen year-old puts herself and he...
19592,tt0074562,Gable and Lombard,1976,5.1,R,131,"Biography, Drama, Romance",601,19161363.0,nm0002089,Sidney J. Furie,"nm0000981,nm0001049,nm0307255,nm0000999","James Brolin,Jill Clayburgh,Allen Garfield,Red...",A biography about the love affair between 1930...

In [47]:
#Q9 what are unique certificates in the dataset?

df['certificate'].nunique()

31

In [48]:
#Q10. how many movies were released each year?
df.groupby("year")["id"].count()

year
1894      1
1898      1
1902      2
1903      1
1913      3
       ...
2018    736
2019    657
2020    467
2021    470
2022    174
Name: id, Length: 114, dtype: int64

In [49]:
df['year'].value_counts().sort_index(ascending=False)

year
2022    174
2021    470
2020    467
2019    657
2018    736
       ...
1913      3
1903      1
1902      2
1898      1
1894      1
Name: count, Length: 114, dtype: int64

In [50]:
## Q11 What are 5 most common genres?

df.groupby("genre")["id"].count().sort_values(ascending = False).head(5)

genre
Action, Crime, Drama      734
Crime, Drama, Thriller    522
Crime, Drama              430
Drama, Thriller           422
Horror                    411
Name: id, dtype: int64

In [51]:
x = df['genre'].str.split(",").explode()
x = x.str.strip()

In [52]:
x.value_counts().sort_values(ascending = False)

genre
Drama          9655
Action         5290
Crime          5244
Comedy         4641
Thriller       4231
Adventure      3313
Horror         3143
Mystery        2211
Romance        1815
Biography      1582
Fantasy        1447
Sci-Fi         1399
Music          1151
Documentary    1001
Family          888
Animation       880
War             861
Western         785
Sport           686
History         531
Film-Noir       335
Short           191
Musical         148
News              9
Reality-TV        1
Game-Show         1
Name: count, dtype: int64

In [ ]:
!python - version

Python 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>